### ISSUE TITLE
Broken polls

### ISSUE THREAD

**Issue by D1Ck3n** [kellerben/dudle#105]
Hi,

since last saturday some of my Polls are broken. it shows only cryptic code and script alerts:

Titel of the poll is changed to "x3ouljcw"

after clicking on the poll it shows:
![dudle_error](https://user-images.githubusercontent.com/28949322/56893606-89ff9800-6a83-11e9-885a-c276fe31d48f.JPG)

i don't know what to do

other polls are working fine :/

Greetings

**Comment by kellerben** [comment]
can you give me the link to the poll? (you can send it to me per e-mail)

**Comment by D1Ck3n** [comment]
Unfortunately, this is not a publicly accessible dudle.

**Comment by kellerben** [comment]
However, the Screenshot you showed is from somebody trying to test an SQL-Injection into the “Title”-Field of the Poll Creation interface. Because the Title cannot be used as url, the url of the poll is set to x3ouljcw. Afterwards, your attacker tried a Cross-Site-Scripting in the Username.
I cannot see any problem coming from the dudle-Application itself… It looks like someone is just testing bad strings…

**Comment by kellerben** [comment]
I think this is no bug
