### ISSUE TITLE
.htaccess references root instead of relative

### ISSUE THREAD

**Issue by jlpoolen** [kellerben/dudle#19]
The .htaccess file references the root of the server, to wit: "/", when it should access the relative path.  If you create a subdirectory "dudle"  under the root directory of the server as recommended by the README  the server  will look one level up for the error.cgi.

https://github.com/kellerben/dudle/blob/master/.htaccess#L20-L22

Removing the "/" on lines 20-22 fixes the problem.

**Comment by kellerben** [comment]
The problem is, that you need an absolute URL when you have an error. Assuming the error.cgi is at http://example.org/dudle/error.cgi and you have a 500 at http://example.org/dudle/somepoll/history.cgi, the apache needs to know where to access the error.cgi…
Another example would be if you want to raise a 404 if some user deleted somepoll. You want to raise the 404 if someone accesses http://example.org/dudle/somepoll/ as well as http://example.org/dudle/somepoll

**Comment by jlpoolen** [comment]
kellerben wrote:

   you need an absolute URL when you have an error

Since the .htaccess files ship with "/" in front of the error files, that necessitates that the installation occur in the root directory, in which case the installation instructions should indicate that installation must be at the root directory, and not in a subdirectory (as I did).

**Comment by kellerben** [comment]
It is not possible to configure Apache to have relative URLs in the ErrorDocument:
https://httpd.apache.org/docs/2.4/custom-error.html
I will write a hint to the Installation README.
